version: '3.8'

services:
  #node-backend:
  #  build: ./backend 
  #  ports:
  #    - "3000:3000"  
  #  depends_on:
  #    - mongodb
  #  environment:
  #    MONGO_URI: "mongodb://mongodb:27017/mydatabase"
  #  networks:
  #    - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./backend/mongo_data:/data/db
      - ./backend/mongo_data:/mongo_data
      - ./backend/mongo_data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.s
    networks:
      - app-network
volumes:
  mongo_data:

networks:
  app-network:
