name: Create Pull Request for Monitoring Request

on:
  push:
    branches:
      - 'monitoring-request-*'  # Trigger only for branches matching this pattern
jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'New Monitoring Request'
          body: |
            This pull request adds a new monitoring request submitted via the form.
          base: main
          branch: ${{ github.ref_name }}